MESSAGES = {
    "en": {
        "welcome": "🌤️ <b>Welcome to Advanced Weather Bot!</b> 🌤️\n\nI'm your comprehensive weather assistant with many features:\n\n🔹 Current weather for any city\n🔹 5-day detailed forecasts\n🔹 City search and suggestions\n🔹 Favorite locations\n🔹 Weather alerts\n🔹 City comparisons\n🔹 Customizable units & settings\n\nChoose a category below or type a city name to get started!",
        "help": "🆘 <b>Weather Bot Commands</b>\n\n📍 <b>Weather Commands:</b>\n• <code>/weather [city]</code> - Current weather\n• <code>/forecast [city]</code> - 5-day forecast\n• <code>/alerts [city]</code> - Weather alerts\n\n🔍 <b>Search & Discovery:</b>\n• <code>/search [query]</code> - Find cities\n• <code>/map [city]</code> - Weather map link\n• <code>/compare city1,city2</code> - Compare cities\n\n⭐ <b>Favorites:</b>\n• <code>/favorites</code> - Show favorite cities\n• <code>/addfav [city]</code> - Add to favorites\n• <code>/removefav [city]</code> - Remove favorite\n\n⚙️ <b>Settings:</b>\n• <code>/settings</code> - Change preferences\n\n💡 <b>Tips:</b>\n• Just type a city name for quick weather\n• Use quotes for cities with spaces: 'New York'\n• Set a default city in settings",
        "specify_city_weather": "Please specify a city! Usage: <code>/weather [city]</code>\nExample: <code>/weather London</code>\nOr set a default city in /settings",
        "specify_city_forecast": "Please specify a city! Usage: <code>/forecast [city]</code>\nExample: <code>/forecast Tokyo</code>",
        "specify_query_search": "Please provide a search query! Usage: <code>/search [query]</code>\nExample: <code>/search paris</code>",
        "no_favorites": "You don't have any favorite cities yet!\nAdd some using <code>/addfav [city]</code>",
        "favorites_list": "⭐ <b>Your Favorite Cities ({count})</b>\n\nClick on any city to get current weather:",
        "specify_city_addfav": "Please specify a city! Usage: <code>/addfav [city]</code>",
        "city_not_found": "🚫 City '{city}' not found. Please check the spelling.",
        "added_favorite": "⭐ Added '{city}' to your favorites!",
        "already_favorite": "'{city}' is already in your favorites!",
        "specify_city_removefav": "Please specify a city! Usage: <code>/removefav [city]</code>",
        "removed_favorite": "🗑️ Removed '{city}' from favorites!",
        "not_in_favorites": "'{city}' is not in your favorites!",
        "settings_menu": "⚙️ <b>Settings</b>\n\n🌡️ Temperature Unit: {unit}\n🌐 Language: {language}\n🏠 Default City: {default_city}\n⭐ Favorite Cities: {fav_count}\n\nClick the buttons below to change settings:",
        "specify_city_alerts": "Please specify a city! Usage: <code>/alerts [city]</code>",
        "alerts_for_city": "⚠️ <b>Weather Alerts for {city}</b>\n\n{alerts_list}\n\n🌡️ Current temp: {temp}",
        "no_alerts": "✅ <b>No Weather Alerts for {city}</b>\n\nCurrent conditions are normal.",
        "error_fetching_alerts": "❌ Could not fetch weather alerts. Please try again later.",
        "specify_cities_compare": "Please specify cities to compare!\nUsage: <code>/compare city1,city2</code>\nExample: <code>/compare London,Paris</code>",
        "not_enough_cities": "Please specify at least 2 cities separated by commas!\nExample: <code>/compare London,Paris</code>",
        "too_many_cities": "You can compare up to 4 cities at once!",
        "error_comparing_weather": "❌ Could not compare weather data. Please try again later.",
        "specify_city_map": "Please specify a city! Usage: <code>/map [city]</code>",
        "error_generating_map": "❌ Could not generate map links. Please try again later.",
        "map_links": "🗺️ <b>Weather Maps for {city}</b>\n\nClick the links below to view interactive weather maps:",
        "no_cities_found_search": "🚫 No cities found matching '{query}'",
        "cities_matching_search": "🔍 <b>Cities matching '{query}':</b>\n\n{city_list}",
        "error_searching_cities": "❌ Could not search for cities. Please try again later.",
        "request_timeout": "⏰ Request timeout. Please try again later.",
        "api_request_failed": "❌ Sorry, I couldn't fetch weather data right now. Please try again later.",
        "unexpected_error": "❌ An unexpected error occurred. Please try again.",
        "city_not_found_weather": "🚫 City '{city}' not found. Please check the spelling and try again.",
        "error_fetching_forecast": "❌ Could not fetch forecast data. Please try again later.",
        "units_celsius": "Celsius (°C)",
        "units_fahrenheit": "Fahrenheit (°F)",
        "default_city_not_set": "Not set",
        "set_default_city_instructions": "🏠 To set a default city, use the command:\n<code>/addfav [city]</code> then come back to settings.\n\nOr just type a city name and I'll remember it!",
        "manage_favorites_menu": "⭐ <b>Manage Favorite Cities</b>\n\nClick to remove a city:",
        "reset_settings_confirm": "✅ All settings have been reset to default!",
        "manage_favorites_back": "⬅️ Back to Settings",
        "add_to_favorites_button": "⭐ Add to Favorites",
        "manage_favorites_button": "⚙️ Manage Favorites",
        "openweather_map_button": "🗺️ OpenWeather Map",
        "Maps_button": "📍 Google Maps",
        "temperature_comparison": "🌡️ <b>Temperature ({unit_symbol})</b>\n",
        "humidity_comparison": "💧 <b>Humidity (%)</b>\n",
        "current_conditions_comparison": "☁️ <b>Current Conditions</b>\n",
        "highlights_comparison": "\n🏅 <b>Highlights</b>\n",
        "hottest": "🔥 Hottest: {city} ({temp:.1f}{unit_symbol})",
        "coldest": "🧊 Coldest: {city} ({temp:.1f}{unit_symbol})",
        "most_humid": "💧 Most Humid: {city} ({humidity}%)",
        "weather_comparison_title": "🏆 <b>Weather Comparison</b>\n\n",
        "units_toggle_button": "🌡️ Units: {unit_name}",
        "language_toggle_button": "🌐 Language: {language_name}",
        "default_city_button": "🏠 Default City: {city_name}",
        "reset_settings_button": "🗑️ Reset All Settings",
        "choose_language": "🌐 <b>Choose your language:</b>",
        "language_set": "🌐 Language set to {language_name}!",
        "english": "English",
        "arabic": "العربية",
        "current_weather_button": "🌤️ Current Weather",
        "five_day_forecast_button": "📊 5-Day Forecast",
        "search_cities_button": "🔍 Search Cities",
        "favorites_button": "⭐ Favorites",
        "settings_button": "⚙️ Settings",
        "weather_in_city": "Current Weather in {city}, {country}",
        "temperature": "Temperature",
        "feels_like": "Feels like",
        "humidity": "Humidity",
        "pressure": "Pressure",
        "wind": "Wind",
        "cloudiness": "Cloudiness",
        "visibility": "Visibility",
        "conditions": "Conditions",
        "sunrise": "Sunrise",
        "sunset": "Sunset",
        "meters_per_second": "m/s",
        "miles_per_hour": "mph",
        "forecast_for_city": "5-Day Forecast for {city}, {country}",
        "extreme_heat_warning": "Extreme Heat Warning!",
        "extreme_cold_warning": "Extreme Cold Warning!",
        "high_wind_alert": "High Wind Alert!",
        "high_humidity_alert": "High Humidity Alert!",
        "thunderstorm_alert": "Thunderstorm Alert!",
        "heavy_rain_alert": "Heavy Rain Alert!",
        "snow_alert": "Snow Alert!",
        "error_fetching_data_any_cities": "❌ Could not fetch weather data for some cities. Please try again later."
    },
    "ar": {
        "welcome": "🌤️ <b>أهلاً بك في بوت الطقس المتقدم!</b> 🌤️\n\nأنا مساعدك الشامل للطقس مع العديد من الميزات:\n\n🔹 الطقس الحالي لأي مدينة\n🔹 توقعات مفصلة لمدة 5 أيام\n🔹 بحث المدن واقتراحاتها\n🔹 المواقع المفضلة\n🔹 تنبيهات الطقس\n🔹 مقارنة المدن\n🔹 وحدات وإعدادات قابلة للتخصيص\n\nاختر فئة أدناه أو اكتب اسم مدينة للبدء!",
        "help": "🆘 <b>أوامر بوت الطقس</b>\n\n📍 <b>أوامر الطقس:</b>\n• <code>/weather [مدينة]</code> - الطقس الحالي\n• <code>/forecast [مدينة]</code> - توقعات 5 أيام\n• <code>/alerts [مدينة]</code> - تنبيهات الطقس\n\n🔍 <b>البحث والاكتشاف:</b>\n• <code>/search [استعلام]</code> - البحث عن مدن\n• <code>/map [مدينة]</code> - رابط خريطة الطقس\n• <code>/compare مدينة1,مدينة2</code> - مقارنة المدن\n\n⭐ <b>المفضلة:</b>\n• <code>/favorites</code> - عرض المدن المفضلة\n• <code>/addfav [مدينة]</code> - إضافة إلى المفضلة\n• <code>/removefav [مدينة]</code> - إزالة من المفضلة\n\n⚙️ <b>الإعدادات:</b>\n• <code>/settings</code> - تغيير التفضيلات\n\n💡 <b>نصائح:</b>\n• فقط اكتب اسم مدينة للحصول على الطقس السريع\n• استخدم علامات الاقتباس للمدن التي تحتوي على مسافات: 'نيويورك'\n• قم بتعيين مدينة افتراضية في الإعدادات",
        "specify_city_weather": "الرجاء تحديد مدينة! الاستخدام: <code>/weather [مدينة]</code>\nمثال: <code>/weather لندن</code>\nأو قم بتعيين مدينة افتراضية في /settings",
        "specify_city_forecast": "الرجاء تحديد مدينة! الاستخدام: <code>/forecast [مدينة]</code>\nمثال: <code>/forecast طوكيو</code>",
        "specify_query_search": "الرجاء تقديم استعلام بحث! الاستخدام: <code>/search [استعلام]</code>\nمثال: <code>/search باريس</code>",
        "no_favorites": "ليس لديك أي مدن مفضلة بعد!\nأضف بعضها باستخدام <code>/addfav [مدينة]</code>",
        "favorites_list": "⭐ <b>مدنك المفضلة ({count})</b>\n\nانقر على أي مدينة للحصول على الطقس الحالي:",
        "specify_city_addfav": "الرجاء تحديد مدينة! الاستخدام: <code>/addfav [مدينة]</code>",
        "city_not_found": "🚫 لم يتم العثور على مدينة '{city}'. يرجى التحقق من الإملاء.",
        "added_favorite": "⭐ تمت إضافة '{city}' إلى مفضلاتك!",
        "already_favorite": "'{city}' موجودة بالفعل في مفضلاتك!",
        "specify_city_removefav": "الرجاء تحديد مدينة! الاستخدام: <code>/removefav [مدينة]</code>",
        "removed_favorite": "🗑️ تمت إزالة '{city}' من المفضلة!",
        "not_in_favorites": "'{city}' ليست في مفضلاتك!",
        "settings_menu": "⚙️ <b>الإعدادات</b>\n\n🌡️ وحدة الحرارة: {unit}\n🌐 اللغة: {language}\n🏠 المدينة الافتراضية: {default_city}\n⭐ المدن المفضلة: {fav_count}\n\nانقر على الأزرار أدناه لتغيير الإعدادات:",
        "specify_city_alerts": "الرجاء تحديد مدينة! الاستخدام: <code>/alerts [مدينة]</code>",
        "alerts_for_city": "⚠️ <b>تنبيهات الطقس لـ {city}</b>\n\n{alerts_list}\n\n🌡️ درجة الحرارة الحالية: {temp}",
        "no_alerts": "✅ <b>لا توجد تنبيهات طقس لـ {city}</b>\n\nالظروف الحالية طبيعية.",
        "error_fetching_alerts": "❌ تعذر جلب تنبيهات الطقس. يرجى المحاولة مرة أخرى لاحقًا.",
        "specify_cities_compare": "الرجاء تحديد المدن للمقارنة!\nالاستخدام: <code>/compare مدينة1,مدينة2</code>\nمثال: <code>/compare لندن,باريس</code>",
        "not_enough_cities": "الرجاء تحديد مدينتين على الأقل مفصولة بفواصل!\nمثال: <code>/compare لندن,باريس</code>",
        "too_many_cities": "يمكنك مقارنة ما يصل إلى 4 مدن في وقت واحد!",
        "error_comparing_weather": "❌ تعذر مقارنة بيانات الطقس. يرجى المحاولة مرة أخرى لاحقًا.",
        "specify_city_map": "الرجاء تحديد مدينة! الاستخدام: <code>/map [مدينة]</code>",
        "error_generating_map": "❌ تعذر إنشاء روابط الخرائط. يرجى المحاولة مرة أخرى لاحقًا.",
        "map_links": "🗺️ <b>خرائط الطقس لـ {city}</b>\n\nانقر على الروابط أدناه لعرض خرائط الطقس التفاعلية:",
        "no_cities_found_search": "🚫 لم يتم العثور على مدن مطابقة لـ '{query}'",
        "cities_matching_search": "🔍 <b>المدن المطابقة لـ '{query}':</b>\n\n{city_list}",
        "error_searching_cities": "❌ تعذر البحث عن مدن. يرجى المحاولة مرة أخرى لاحقًا.",
        "request_timeout": "⏰ انتهت مهلة الطلب. يرجى المحاولة مرة أخرى لاحقًا.",
        "api_request_failed": "❌ عذراً، لم أتمكن من جلب بيانات الطقس الآن. يرجى المحاولة مرة أخرى لاحقًا.",
        "unexpected_error": "❌ حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.",
        "city_not_found_weather": "🚫 لم يتم العثور على مدينة '{city}'. يرجى التحقق من الإملاء والمحاولة مرة أخرى.",
        "error_fetching_forecast": "❌ تعذر جلب بيانات التوقعات. يرجى المحاولة مرة أخرى لاحقًا.",
        "units_celsius": "مئوية (°م)",
        "units_fahrenheit": "فهرنهايت (°ف)",
        "default_city_not_set": "لم يتم التعيين",
        "set_default_city_instructions": "🏠 لتعيين مدينة افتراضية، استخدم الأمر:\n<code>/addfav [مدينة]</code> ثم ارجع إلى الإعدادات.\n\nأو فقط اكتب اسم مدينة وسأتذكرها!",
        "manage_favorites_menu": "⭐ <b>إدارة المدن المفضلة</b>\n\nانقر لإزالة مدينة:",
        "reset_settings_confirm": "✅ تم إعادة تعيين جميع الإعدادات إلى الافتراضي!",
        "manage_favorites_back": "⬅️ العودة إلى الإعدادات",
        "add_to_favorites_button": "⭐ إضافة إلى المفضلة",
        "manage_favorites_button": "⚙️ إدارة المفضلة",
        "openweather_map_button": "🗺️ خريطة OpenWeather",
        "Maps_button": "📍 خرائط جوجل",
        "temperature_comparison": "🌡️ <b>درجة الحرارة ({unit_symbol})</b>\n",
        "humidity_comparison": "💧 <b>الرطوبة (%)</b>\n",
        "current_conditions_comparison": "☁️ <b>الظروف الحالية</b>\n",
        "highlights_comparison": "\n🏅 <b>النقاط الرئيسية</b>\n",
        "hottest": "🔥 الأكثر حرارة: {city} ({temp:.1f}{unit_symbol})",
        "coldest": "🧊 الأبرد: {city} ({temp:.1f}{unit_symbol})",
        "most_humid": "💧 الأكثر رطوبة: {city} ({humidity}%)",
        "weather_comparison_title": "🏆 <b>مقارنة الطقس</b>\n\n",
        "units_toggle_button": "🌡️ الوحدات: {unit_name}",
        "language_toggle_button": "🌐 اللغة: {language_name}",
        "default_city_button": "🏠 المدينة الافتراضية: {city_name}",
        "reset_settings_button": "🗑️ إعادة تعيين جميع الإعدادات",
        "choose_language": "🌐 <b>اختر لغتك:</b>",
        "language_set": "🌐 تم تعيين اللغة إلى {language_name}!",
        "english": "الإنجليزية",
        "arabic": "العربية",
        "current_weather_button": "🌤️ الطقس الحالي",
        "five_day_forecast_button": "📊 توقعات 5 أيام",
        "search_cities_button": "🔍 البحث عن مدن",
        "favorites_button": "⭐ المفضلة",
        "settings_button": "⚙️ الإعدادات",
        "weather_in_city": "الطقس الحالي في {city}, {country}",
        "temperature": "درجة الحرارة",
        "feels_like": "الشعور كأن",
        "humidity": "الرطوبة",
        "pressure": "الضغط",
        "wind": "الرياح",
        "cloudiness": "الغيوم",
        "visibility": "الرؤية",
        "conditions": "الظروف",
        "sunrise": "شروق الشمس",
        "sunset": "غروب الشمس",
        "meters_per_second": "م/ث",
        "miles_per_hour": "ميل/ساعة",
        "forecast_for_city": "توقعات 5 أيام لـ {city}, {country}",
        "extreme_heat_warning": "تحذير من حرارة شديدة!",
        "extreme_cold_warning": "تحذير من برد شديد!",
        "high_wind_alert": "تحذير من رياح قوية!",
        "high_humidity_alert": "تحذير من رطوبة عالية!",
        "thunderstorm_alert": "تحذير من عاصفة رعدية!",
        "heavy_rain_alert": "تحذير من أمطار غزيرة!",
        "snow_alert": "تحذير من تساقط ثلوج!",
        "error_fetching_data_any_cities": "❌ تعذر جلب بيانات الطقس لبعض المدن. يرجى المحاولة مرة أخرى لاحقًا."
    }
}

def get_localized_message(user_language: str, key: str, **kwargs) -> str:
    """Get a localized message based on user's language."""
    return MESSAGES.get(user_language, MESSAGES["en"]).get(key, MESSAGES["en"][key]).format(**kwargs)